package gvs.enums;

public enum ProductItemType {
    CONTENT, FINISHED, UPDATE_PHOTO, UPDATE_CONTENT, ADD_FILE, UPDATE_SELECT, UPDATE_ACTIVATE, GET_PHONE, GET_LOCATION,
    KEY_NAME, NAME, CATEGORY_NAME, PRICE, ALL_PRICE, AMOUNT, ALL_AMOUNT, ACITVE, WEIGHT_TYPE, COUNT, CONFIRMED, DELETE, SEE, PHOTO,
    SELL_TYPE, MESSAGE, MESSAGE_PHOTO_MES,MESSAGE_PHOTO_PHO, MES_PHOTO, UPDATE_WEIGHT_TYPE, UPDATE_PRICE, UPDATE_ALL_PRICE, UPDATE_AMOUNT,
    UPDATE_ALL_AMOUNT, UPDATE_NAME, UPDATE_CATEGORY, UPDATE_SELL_TYPE, UPDATE_COUNT, MES_VIDEO,
    REPORT_PRODUCT, REPORT_USER, ABOUT_EDIT
}
